server:
  port: ${PORT:8080}

spring:
  application:
    name: cyclothymic
    
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}

logging:
  level:
    com.todd.cyclothymic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
# Profilo per Railway (production)
spring:
  config:
    activate:
      on-profile: railway
      
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  h2:
    console:
      enabled: false
